name: Manually deploy
on:
  repository_dispatch:
    types: [updated_post]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    # ←★ ここにまとめて書くと Build も Deploy も使える
    env:
      NEXT_PUBLIC_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
      NEXT_PUBLIC_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4   # v4 に更新推奨

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'        # 16 は EOL、20 LTS 推奨
          cache: 'npm'

      - name: Install dependencies
        run: npm ci                 # npm install より再現性が高い

      - name: Build
        run: npm run build

      # Debug 用に secrets を echo するとログに平文で残るので除去！
      # - name: Debug
      #   run: echo "CI 環境変数は渡っています"

      - name: Deploy
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region ap-northeast-1 ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete
          echo "AWS CF reset"
          aws cloudfront create-invalidation \
            --region ap-northeast-1 \
            --distribution-id ${{ secrets.AWS_CF_ID }} \
            --paths "/*"
